name:                unroll-plugin
version:             1.0
github:              "batterseapower/unroll-plugin"
license:             BSD3
author:              "Max Bolingbroke"
maintainer:          "batterseapower@hotmail.com"
copyright:           "2009 Max Bolingbroke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/unroll-plugin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - syb
    - template-haskell
    - ghc
    - ghc-prim

